configfilepath: /Users/kaanyagci/Documents/makepad/hfd/.concom.yml
path: /Users/kaanyagci/Documents/makepad/hfd
version: 0.0.1
scopes:
    - name: ios
      description: All changes related to the iOS components
    - name: android
      description: All changes related to the Android components
    - name: web
      description: All changes related to the web components
    - name: core
      description: All changes related to the core CLI code
    - name: bin
      description: All changes related to the Dart scripts
    - name: struct
      description: All changes related to the structs of code
    - name: adapters
      description: All changes related to adapters
conventions:
    - name: build
      description: Changes that affect the build system or external dependencies
    - name: ci
      description: Changes to our CI configuration files and scripts
    - name: docs
      description: Documentation only changes
    - name: feat
      description: A new feature
    - name: revert
      description: 'If the commit reverts a previous commit, it should begin with revert: , followed by the header of the reverted commit. In the body it should say: This reverts commit <hash>., where the hash is the SHA of the commit being reverted.'
    - name: fix
      description: A bug fix
    - name: perf
      description: A code change that improves performance
    - name: refactor
      description: A code change that neither fixes a bug nor adds a feature
    - name: style
      description: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc)
    - name: test
      description: Adding missing tests or correcting existing tests
